### ISSUE TITLE
Sync does not work

### ISSUE THREAD

**Issue by bpinto** [mickaelperrin/docker-magic-sync#1]
Logs:

```
...
magic-sync_1  | 2016-07-19 18:29:15,738 INFO reaped unknown pid 48
magic-sync_1  | 2016-07-19 18:29:18,749 INFO spawned: 'unison--src-project' with pid 49
magic-sync_1  | 2016-07-19 18:29:19,742 INFO exited: unison--src-project (exit status 3; not expected)
magic-sync_1  | 2016-07-19 18:29:19,757 INFO gave up: unison--src-project entered FATAL state, too many start retries too quickly
magic-sync_1  | 2016-07-19 18:29:19,757 INFO reaped unknown pid 50
```

Configuration:

```
app:
...
  volumes:
    - /src/project

magic-sync:
    image: mickaelperrin/docker-magic-sync:latest
    environment:
      - SYNC_USER=bpinto
      - SYNC_UID=501
      - SYNC_IGNORE=.git
      - MAXIMUM_INOTIFY_WATCHES=524288
    volumes:
      - .:/src/project.magic
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from:
      - app
    privileged: true
```
