### ISSUE TITLE
I would like to ask if i want to mount named volume in container to sync folder

### ISSUE THREAD

**Issue by lyquocphong** [mickaelperrin/docker-magic-sync#14]
```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.5-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    build:
      context: .
      dockerfile: moodle.Dockerfile
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=admin123#
      - MOODLE_EMAIL=lyquocphong+admin@gmail.com
      - MOODLE_SITE_NAME=Bitnami Moodle 3.9
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
      - 'phpu_moodledata_data:/bitnami/phpu_moodledata'
    depends_on:
      - mariadb
  magic-sync:
    image: mickaelperrin/docker-magic-sync:latest
    environment:
    - SYNC_USER=www-data
    - SYNC_UID=33
    - SYNC_IGNORE_NAMES=.idea:.git
    - SYNC_IGNORE_PATHS=www/example:www2/example2
    #- MAXIMUM_INOTIFY_WATCHES=524288
    volumes:
    # Configure here the mappings between your host and the container.
    # Simply add a `.magic` extension to the volume path in the container.
    # the :cached is optional, but we hope it improves inotify events.
    - ./sync/moodle_data:/bitnami/moodle.magic:cached
    # this is needed for automatic discovery of mounted volumes in this container.
    - /var/run/docker.sock:/tmp/docker.sock:ro
    # If you want to configure USER / UID / IGNORE by volumes, you can use a simple YAML configuration file
    # - ./docker-syncs.yml:/sync-entrypoint.d/docker-syncs.yml
    volumes_from:
    - moodle
    # Privilegied mode is needed if you want to increase the maximum inotify watches for very large synced folders
    # by setting the ENV var MAXIMUM_INOTIFY_WATCHES.
    #privileged: true
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
  phpu_moodledata_data:
    driver: local
```

I would like to sync the moodle_data to host folder. I always get error:
 Warning: No archive files were found for these roots, whose canonical names are:
magic-sync_1  |         /bitnami/moodle.magic
magic-sync_1  |         /bitnami/moodle
