### ISSUE TITLE
Docker-compose version 3 

### ISSUE THREAD

**Issue by jarzebowsky** [mickaelperrin/docker-magic-sync#9]
What approach should be taken to make it working with docker-compose version 3 is it even possible in actual state?

**Comment by thtas** [comment]
Maybe something like this?

```yml
version: "3"

services:
  php:
    volumes:
      - data:/var/www/html

  magic-sync:
    image: mickaelperrin/docker-magic-sync:latest
    environment:
      - SYNC_USER=www-data
      - SYNC_UID=1000
      - SYNC_IGNORE_NAMES=.idea:.git
    volumes:
      - data:/var/www/html
      - ./:/var/www/html.magic:cached
      - /var/run/docker.sock:/tmp/docker.sock:ro
volumes:
  data:
```
